import asyncio
import socket
import ssl
import time
import re
from typing import Dict, Any, List, Optional, Tuple
from urllib.parse import urlparse
import httpx

from app.core.logging import logger

WAF_SIGNATURES = [
    {
        "provider": "Cloudflare",
        "headers": ["cf-ray", "cf-cache-status", "cf-request-id", "cf-mitigated"],
        "server": r"cloudflare",
        "cookies": ["__cf_bm", "cf_clearance", "__cflb"],
        "body": [r"Attention Required! \| Cloudflare", r"challenge-platform", r"turnstile", r"cf-browser-verification", r"cloudflare-static/rocket-loader"],
        "confidence_weights": {"server": 0.4, "headers": 0.5, "cookies": 0.4, "body": 0.6}
    },
    {
        "provider": "Akamai",
        "headers": ["x-akamai-transformed", "x-akamai-request-id", "x-akamai-session-info", "akamai-grn"],
        "server": r"AkamaiGHost|AkamaiNetStorage",
        "cookies": ["ak_bmsc", "bm_sz", "_abck", "bm_mi"],
        "body": [r"Akamai Bot Manager", r"akamai-challenge", r"Reference #[0-9a-f\.]+", r"ak_bmsc"],
        "confidence_weights": {"server": 0.5, "headers": 0.5, "cookies": 0.5, "body": 0.6}
    },
    {
        "provider": "AWS WAF / CloudFront",
        "headers": ["x-amzn-waf-action", "x-amzn-errortype", "x-amz-cf-id", "x-amz-cf-pop"],
        "server": r"CloudFront|awselb",
        "cookies": ["aws-waf-token"],
        "body": [r"aws-waf-captcha", r"AWS WAF Blocked", r"CloudFront 403 Forbidden"],
        "confidence_weights": {"server": 0.3, "headers": 0.6, "cookies": 0.5, "body": 0.6}
    },
    {
        "provider": "Imperva Incapsula",
        "headers": ["x-iinfo", "x-cdn", "x-incap-sess"],
        "server": r"Incapsula",
        "cookies": ["incap_ses", "visid_incap", "nlbi_"],
        "body": [r"_Incapsula_Resource", r"Incapsula incident ID", r"Request unsuccessful\. Incapsula"],
        "confidence_weights": {"server": 0.5, "headers": 0.5, "cookies": 0.5, "body": 0.6}
    },
    {
        "provider": "Fastly / Signal Sciences",
        "headers": ["x-sigsci-request-id", "fastly-io-info", "x-fastly-request-id", "x-served-by"],
        "server": r"Fastly",
        "cookies": ["sigsci-user"],
        "body": [r"Fastly error: unknown domain", r"Signal Sciences"],
        "confidence_weights": {"server": 0.4, "headers": 0.5, "cookies": 0.4, "body": 0.5}
    },
    {
        "provider": "F5 BIG-IP / ASM",
        "headers": ["x-cnection", "x-wa-info"],
        "server": r"BigIP|BIG-IP",
        "cookies": ["bigipserver", "ts-cookie", "TS[0-9a-f]{6,8}"],
        "body": [r"The requested URL was rejected\. Please consult with your administrator\.", r"TS[0-9a-f]{20,}"],
        "confidence_weights": {"server": 0.5, "headers": 0.4, "cookies": 0.6, "body": 0.6}
    },
    {
        "provider": "Sucuri",
        "headers": ["x-sucuri-id", "x-sucuri-cache", "x-sucuri-block"],
        "server": r"Sucuri|Cloudproxy",
        "cookies": ["sucuri_cloudproxy"],
        "body": [r"Access Denied - Sucuri Website Firewall", r"sucuri\.net"],
        "confidence_weights": {"server": 0.5, "headers": 0.6, "cookies": 0.5, "body": 0.6}
    },
    {
        "provider": "ModSecurity / OWASP CRS",
        "headers": ["mod_security", "modsecurity"],
        "server": r"mod_security|ModSecurity",
        "cookies": [],
        "body": [r"ModSecurity Action", r"This error was generated by Mod_Security", r"406 Not Acceptable"],
        "confidence_weights": {"server": 0.6, "headers": 0.6, "cookies": 0.3, "body": 0.5}
    },
    {
        "provider": "PerimeterX / HUMAN",
        "headers": ["x-px-", "px-challenge"],
        "server": r"",
        "cookies": ["_px", "_px2", "_px3", "_pxhd"],
        "body": [r"Press & Hold", r"px-captcha", r"perimeterx", r"client\.perimeterx\.net"],
        "confidence_weights": {"server": 0.2, "headers": 0.6, "cookies": 0.6, "body": 0.7}
    }
]

CAPTCHA_SIGNATURES = [
    {"name": "Cloudflare Turnstile / Challenge", "patterns": [r"challenges\.cloudflare\.com/turnstile", r"cf-challenge", r"challenge-platform/scripts", r"turnstile\.render"]},
    {"name": "Google reCAPTCHA", "patterns": [r"google\.com/recaptcha/api", r"g-recaptcha", r"recaptcha/releases"]},
    {"name": "hCaptcha", "patterns": [r"hcaptcha\.com/1/api", r"h-captcha", r"js\.hcaptcha\.com"]},
    {"name": "PerimeterX / HUMAN Challenge", "patterns": [r"client\.perimeterx\.net", r"px-captcha", r"_pxAction"]},
    {"name": "Akamai Bot Manager Challenge", "patterns": [r"akamai-challenge", r"_abck", r"ak_bmsc", r"akam\.js"]},
    {"name": "DataDome Anti-Bot Challenge", "patterns": [r"api-js\.datadome\.co", r"datadome\.js", r"datadome-captcha"]},
    {"name": "AWS WAF Challenge / Captcha", "patterns": [r"aws-waf-captcha", r"aws-waf-token", r"challenge\.awswaf\.com"]}
]


class DASTConnectivityDiagnostics:
    """
    Executes non-evasive pre-scan target verification across 12 diagnostic dimensions.
    Collects full connectivity, TLS handshake, redirect chains, passive WAF evidence,
    rate-limiting, auth barriers, and bot challenges.
    """

    def __init__(self, timeout: float = 6.0):
        self.timeout = timeout

    async def run_diagnostics(self, target_url: str, custom_headers: Optional[Dict[str, str]] = None) -> Dict[str, Any]:
        """Run all 12 pre-scan connectivity & blocking checks."""
        parsed = urlparse(target_url)
        scheme = parsed.scheme.lower() if parsed.scheme else "https"
        hostname = parsed.hostname or ""
        port = parsed.port or (443 if scheme == "https" else 80)

        # 1. DNS Resolution
        dns_res = await self._check_dns(hostname)

        # 2. TCP Connectivity
        tcp_res = await self._check_tcp(hostname, port)

        # 3. TLS Handshake (if HTTPS)
        tls_res = await self._check_tls(hostname, port) if scheme == "https" else {
            "status": "N/A",
            "protocol": "HTTP (Unencrypted)",
            "cipher": None,
            "cert_valid": None,
            "issuer": None,
            "subject": None,
            "san": [],
            "expires": None,
            "error": None
        }

        # 4, 5, 6, 7, 8, 9, 10, 11, 12. HTTP probing & signature analysis
        http_res = await self._probe_http(target_url, custom_headers)

        # Passive WAF detection
        waf_res = self._detect_waf(http_res)

        # Passive CAPTCHA / Challenge detection
        captcha_res = self._detect_captcha(http_res)

        # Passive Rate Limit Analysis
        ratelimit_res = self._analyze_rate_limits(http_res)

        # Passive Auth Requirement Analysis
        auth_res = self._analyze_auth_requirement(http_res)

        # Determine Target Reachability & Application Access
        reachability = "REACHABLE" if (dns_res.get("status") == "SUCCESS" and tcp_res.get("status") == "CONNECTED" and http_res.get("status_code")) else "UNREACHABLE"
        
        access_level = "UNRESTRICTED"
        access_reasons = []

        if reachability == "UNREACHABLE":
            access_level = "BLOCKED"
            access_reasons.append("Target is unreachable over network / DNS failure.")
        else:
            status_code = http_res.get("status_code", 0)
            if status_code in [401, 407]:
                access_level = "AUTH_REQUIRED"
                access_reasons.append(f"Authentication required (HTTP {status_code}).")
            elif status_code == 403:
                access_level = "LIMITED"
                access_reasons.append(f"HTTP 403 Forbidden received on entrypoint.")
            elif status_code == 429:
                access_level = "LIMITED"
                access_reasons.append(f"HTTP 429 Too Many Requests received on initial probe.")
            
            if waf_res.get("detected"):
                if access_level == "UNRESTRICTED":
                    access_level = "LIMITED"
                access_reasons.append(f"WAF / Bot Protection detected ({waf_res.get('provider')}).")

            if captcha_res.get("detected"):
                access_level = "LIMITED"
                access_reasons.append(f"Active Bot / CAPTCHA challenge detected ({', '.join(captcha_res.get('challenges', []))}).")

        # Assessment Impact & Finding Confidence
        finding_confidence = "FULL" if access_level == "UNRESTRICTED" else "LIMITED"
        assessment_impact = (
            "Standard DAST coverage can proceed normally."
            if access_level == "UNRESTRICTED"
            else "Active DAST coverage may be incomplete or restricted due to upstream security controls (WAF, Rate Limiting, CAPTCHA, or Authentication barriers)."
        )

        diagnostic_recommendation = (
            "Target is directly accessible."
            if access_level == "UNRESTRICTED"
            else "Configure an authorized scanner IP allowlist or provide an approved authenticated scanning configuration to achieve complete assessment coverage."
        )

        diagnostics_payload = {
            "target_url": target_url,
            "hostname": hostname,
            "port": port,
            "scheme": scheme,
            "timestamp": time.time(),
            "reachability": reachability,
            "access_level": access_level,
            "access_reasons": access_reasons,
            "finding_confidence": finding_confidence,
            "assessment_impact": assessment_impact,
            "diagnostic_recommendation": diagnostic_recommendation,
            "checks": {
                "1_dns_resolution": dns_res,
                "2_tcp_connectivity": tcp_res,
                "3_tls_handshake": tls_res,
                "4_http_status": {
                    "initial_status_code": http_res.get("status_code"),
                    "status_text": http_res.get("status_text")
                },
                "5_redirect_chain": http_res.get("redirect_chain", []),
                "6_response_headers": http_res.get("sanitized_headers", {}),
                "7_response_time_ms": http_res.get("response_time_ms", 0),
                "8_server_cdn_info": {
                    "server_header": http_res.get("server_header"),
                    "cdn_provider": waf_res.get("provider") if waf_res.get("detected") else "None detected",
                    "edge_headers": http_res.get("edge_headers", {})
                },
                "9_waf_indicators": waf_res,
                "10_rate_limit_responses": ratelimit_res,
                "11_authentication_requirement": auth_res,
                "12_captcha_challenge_indicators": captcha_res
            }
        }

        return diagnostics_payload

    async def _check_dns(self, hostname: str) -> Dict[str, Any]:
        """Check DNS IPv4/IPv6 resolution and lookup latency."""
        start = time.time()
        try:
            loop = asyncio.get_event_loop()
            addrinfo = await loop.run_in_executor(None, socket.getaddrinfo, hostname, None)
            resolved_ips = list(set([item[4][0] for item in addrinfo if item and item[4]]))
            elapsed_ms = round((time.time() - start) * 1000, 2)

            return {
                "status": "SUCCESS",
                "resolved_ips": resolved_ips,
                "latency_ms": elapsed_ms,
                "ip_count": len(resolved_ips),
                "error": None
            }
        except Exception as e:
            elapsed_ms = round((time.time() - start) * 1000, 2)
            return {
                "status": "FAILED",
                "resolved_ips": [],
                "latency_ms": elapsed_ms,
                "ip_count": 0,
                "error": str(e)
            }

    async def _check_tcp(self, hostname: str, port: int) -> Dict[str, Any]:
        """Test TCP socket connection and measure connect latency."""
        start = time.time()
        try:
            loop = asyncio.get_event_loop()
            def test_connect():
                sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
                sock.settimeout(2.5)
                sock.connect((hostname, port))
                sock.close()
            await loop.run_in_executor(None, test_connect)
            elapsed_ms = round((time.time() - start) * 1000, 2)
            return {
                "status": "CONNECTED",
                "latency_ms": elapsed_ms,
                "port": port,
                "error": None
            }
        except socket.timeout:
            elapsed_ms = round((time.time() - start) * 1000, 2)
            return {
                "status": "TIMED_OUT",
                "latency_ms": elapsed_ms,
                "port": port,
                "error": "TCP connection timed out."
            }
        except Exception as e:
            elapsed_ms = round((time.time() - start) * 1000, 2)
            return {
                "status": "FAILED",
                "latency_ms": elapsed_ms,
                "port": port,
                "error": str(e)
            }

    async def _check_tls(self, hostname: str, port: int) -> Dict[str, Any]:
        """Perform TLS handshake and inspect certificate & protocol version."""
        start = time.time()
        try:
            loop = asyncio.get_event_loop()
            def tls_handshake():
                ctx = ssl.create_default_context()
                ctx.check_hostname = True
                ctx.verify_mode = ssl.CERT_REQUIRED
                with socket.create_connection((hostname, port), timeout=2.5) as sock:
                    with ctx.wrap_socket(sock, server_hostname=hostname) as ssock:
                        cert = ssock.getpeercert()
                        cipher = ssock.cipher()
                        version = ssock.version()
                        return cert, cipher, version

            cert, cipher, version = await loop.run_in_executor(None, tls_handshake)
            elapsed_ms = round((time.time() - start) * 1000, 2)

            san = []
            if cert and "subjectAltName" in cert:
                san = [item[1] for item in cert["subjectAltName"] if len(item) > 1]

            issuer_dict = {}
            if cert and "issuer" in cert:
                for tuple_item in cert["issuer"]:
                    for key, val in tuple_item:
                        issuer_dict[key] = val

            issuer_name = issuer_dict.get("organizationName") or issuer_dict.get("commonName") or "Unknown Issuer"

            return {
                "status": "SUCCESS",
                "protocol": version,
                "cipher": cipher[0] if cipher else "Unknown",
                "cert_valid": True,
                "issuer": issuer_name,
                "san": san[:8],
                "expires": cert.get("notAfter") if cert else None,
                "handshake_latency_ms": elapsed_ms,
                "error": None
            }
        except ssl.SSLCertVerificationError as ssl_err:
            elapsed_ms = round((time.time() - start) * 1000, 2)
            return {
                "status": "CERT_UNVERIFIED",
                "protocol": "TLS Handshake Failed",
                "cipher": None,
                "cert_valid": False,
                "issuer": "Untrusted/Self-Signed",
                "san": [],
                "expires": None,
                "handshake_latency_ms": elapsed_ms,
                "error": f"Certificate verification error: {str(ssl_err)}"
            }
        except Exception as e:
            elapsed_ms = round((time.time() - start) * 1000, 2)
            return {
                "status": "FAILED",
                "protocol": "None",
                "cipher": None,
                "cert_valid": False,
                "issuer": None,
                "san": [],
                "expires": None,
                "handshake_latency_ms": elapsed_ms,
                "error": str(e)
            }

    async def _probe_http(self, target_url: str, custom_headers: Optional[Dict[str, str]] = None) -> Dict[str, Any]:
        """Perform initial HTTP probe and record redirect chain, headers, and body signatures."""
        headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36 Sentinal-DAST-Diagnostics/2.0",
            "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
            "Accept-Language": "en-US,en;q=0.9",
        }
        if custom_headers:
            headers.update(custom_headers)

        redirect_chain = []
        start = time.time()

        try:
            async with httpx.AsyncClient(
                verify=False,
                timeout=httpx.Timeout(4.0, connect=2.0),
                follow_redirects=True,
                max_redirects=10
            ) as client:
                resp = await client.get(target_url, headers=headers)
                elapsed_ms = round((time.time() - start) * 1000, 2)

                # Capture redirect history
                for i, r in enumerate(resp.history, start=1):
                    redirect_chain.append({
                        "hop": i,
                        "url": str(r.url),
                        "status_code": r.status_code,
                        "location": r.headers.get("location")
                    })

                # Sanitize response headers
                raw_headers = dict(resp.headers)
                sanitized_headers = {}
                edge_headers = {}
                sensitive_keys = {"set-cookie", "authorization", "x-auth-token"}

                for k, v in raw_headers.items():
                    k_lower = k.lower()
                    if k_lower in sensitive_keys:
                        sanitized_headers[k] = "[REDACTED_SECURITY_DATA]"
                    else:
                        sanitized_headers[k] = v

                    if any(p in k_lower for p in ["cf-", "x-amz", "akamai", "fastly", "incap", "sucuri", "x-cdn", "server"]):
                        edge_headers[k] = v

                # Extract cookies list
                cookie_names = [c.name for c in resp.cookies.jar] if hasattr(resp.cookies, "jar") else list(resp.cookies.keys())

                return {
                    "status_code": resp.status_code,
                    "status_text": resp.reason_phrase if hasattr(resp, "reason_phrase") else str(resp.status_code),
                    "response_time_ms": elapsed_ms,
                    "final_url": str(resp.url),
                    "redirect_chain": redirect_chain,
                    "server_header": resp.headers.get("server", "Not Advertised"),
                    "raw_headers": raw_headers,
                    "sanitized_headers": sanitized_headers,
                    "edge_headers": edge_headers,
                    "cookies": cookie_names,
                    "body_snippet": resp.text[:4000] if resp.text else ""
                }
        except httpx.HTTPError as http_err:
            elapsed_ms = round((time.time() - start) * 1000, 2)
            return {
                "status_code": 0,
                "status_text": "HTTP Connection Failed",
                "response_time_ms": elapsed_ms,
                "final_url": target_url,
                "redirect_chain": [],
                "server_header": "Unknown",
                "raw_headers": {},
                "sanitized_headers": {},
                "edge_headers": {},
                "cookies": [],
                "body_snippet": "",
                "error": str(http_err)
            }
        except Exception as e:
            elapsed_ms = round((time.time() - start) * 1000, 2)
            return {
                "status_code": 0,
                "status_text": "Probe Error",
                "response_time_ms": elapsed_ms,
                "final_url": target_url,
                "redirect_chain": [],
                "server_header": "Unknown",
                "raw_headers": {},
                "sanitized_headers": {},
                "edge_headers": {},
                "cookies": [],
                "body_snippet": "",
                "error": str(e)
            }

    def _detect_waf(self, http_res: Dict[str, Any]) -> Dict[str, Any]:
        """Passively detect WAF / CDN indicators and calculate evidence-based confidence."""
        server = http_res.get("server_header", "")
        headers = http_res.get("raw_headers", {})
        header_keys = [k.lower() for k in headers.keys()]
        cookies = [c.lower() for c in http_res.get("cookies", [])]
        body = http_res.get("body_snippet", "")
        status_code = http_res.get("status_code", 0)

        best_match = {
            "detected": False,
            "provider": "None",
            "confidence": "NONE",
            "evidence": [],
            "score": 0.0
        }

        for sig in WAF_SIGNATURES:
            evidence = []
            score = 0.0

            # 1. Server Header Match
            if sig.get("server") and re.search(sig["server"], server, re.IGNORECASE):
                evidence.append(f"Server header matches '{server}'")
                score += sig["confidence_weights"].get("server", 0.4)

            # 2. Header matches
            matched_hdrs = []
            for h in sig.get("headers", []):
                if any(h in hk for hk in header_keys):
                    matched_hdrs.append(h)
            if matched_hdrs:
                evidence.append(f"WAF response headers present: {', '.join(matched_hdrs[:3])}")
                score += sig["confidence_weights"].get("headers", 0.5)

            # 3. Cookie matches
            matched_cookies = []
            for c in sig.get("cookies", []):
                if any(re.search(c, ck, re.IGNORECASE) for ck in cookies):
                    matched_cookies.append(c)
            if matched_cookies:
                evidence.append(f"WAF cookies present: {', '.join(matched_cookies[:3])}")
                score += sig["confidence_weights"].get("cookies", 0.4)

            # 4. Body matches
            matched_body_patterns = []
            for b in sig.get("body", []):
                if re.search(b, body, re.IGNORECASE):
                    matched_body_patterns.append(b)
            if matched_body_patterns:
                evidence.append("WAF / challenge signature matched in HTTP response body")
                score += sig["confidence_weights"].get("body", 0.6)

            # 5. Status code 403/429 boost if headers present
            if status_code in [403, 429] and (matched_hdrs or matched_cookies):
                score += 0.2

            if score > best_match["score"] and score >= 0.4:
                confidence = "HIGH" if score >= 0.8 else ("MEDIUM" if score >= 0.5 else "LOW")
                best_match = {
                    "detected": True,
                    "provider": sig["provider"],
                    "confidence": confidence,
                    "evidence": evidence,
                    "score": round(score, 2)
                }

        # Fallback generic WAF detection if 403/429 on clean request without specific vendor match
        if not best_match["detected"] and status_code in [403, 406, 429]:
            best_match = {
                "detected": True,
                "provider": "Generic WAF / Gateway Restriction",
                "confidence": "LOW",
                "evidence": [f"Initial probe returned HTTP {status_code} on legitimate benign request."],
                "score": 0.4
            }

        return best_match

    def _detect_captcha(self, http_res: Dict[str, Any]) -> Dict[str, Any]:
        """Detect presence of CAPTCHA or interactive challenge screens."""
        body = http_res.get("body_snippet", "")
        detected_challenges = []
        evidence = []

        for cap in CAPTCHA_SIGNATURES:
            for pattern in cap["patterns"]:
                if re.search(pattern, body, re.IGNORECASE):
                    detected_challenges.append(cap["name"])
                    evidence.append(f"Matched pattern '{pattern}' associated with {cap['name']}")
                    break

        # Check for title indicators
        if re.search(r"<title>.*(Just a moment|Attention Required|Security Challenge|Access Denied|Cloudflare|Bot Protection).*</title>", body, re.IGNORECASE):
            evidence.append("HTML page title contains bot challenge indicator")

        is_detected = len(detected_challenges) > 0 or len(evidence) > 0
        return {
            "detected": is_detected,
            "challenges": list(set(detected_challenges)),
            "evidence": evidence
        }

    def _analyze_rate_limits(self, http_res: Dict[str, Any]) -> Dict[str, Any]:
        """Inspect HTTP response headers and status codes for rate-limiting constraints."""
        status_code = http_res.get("status_code", 0)
        headers = http_res.get("raw_headers", {})
        
        is_rate_limited = status_code == 429
        retry_after = headers.get("retry-after") or headers.get("Retry-After")
        
        limit_headers = {}
        for k, v in headers.items():
            if any(term in k.lower() for term in ["ratelimit", "rate-limit", "retry-after", "x-throttle"]):
                limit_headers[k] = v

        return {
            "rate_limited_on_probe": is_rate_limited,
            "status_code": status_code,
            "retry_after": retry_after,
            "rate_limit_headers": limit_headers
        }

    def _analyze_auth_requirement(self, http_res: Dict[str, Any]) -> Dict[str, Any]:
        """Analyze whether the target requires authentication on its entrypoint."""
        status_code = http_res.get("status_code", 0)
        headers = http_res.get("raw_headers", {})
        body = http_res.get("body_snippet", "")
        final_url = http_res.get("final_url", "")

        auth_required = status_code in [401, 407]
        www_authenticate = headers.get("www-authenticate") or headers.get("WWW-Authenticate")
        
        # Check for login redirect
        is_login_redirect = any(term in final_url.lower() for term in ["/login", "/signin", "/auth", "/oauth", "/sso", "/accounts"])
        
        # Check for password input in HTML body
        has_login_form = bool(re.search(r'type=["\']password["\']', body, re.IGNORECASE))

        return {
            "auth_required": auth_required or is_login_redirect,
            "status_code": status_code,
            "www_authenticate_header": www_authenticate,
            "login_redirect_detected": is_login_redirect,
            "login_form_detected": has_login_form,
            "auth_mechanism": "HTTP_BASIC_OR_BEARER" if www_authenticate else ("FORM_BASED_AUTH" if (is_login_redirect or has_login_form) else "NONE")
        }


# Global diagnostic helper instance
dast_diagnostics = DASTConnectivityDiagnostics()
